`BitAnd` and `AndNot` improvements
tczajka/ibig-rs pull request #10
Opened 2022-05-08 01:27 UTC by kakogi

Added `AndNot<UBig> for $t` and `AndNot<IBig> for $t`
Added benchmark for `IBig & u64`
Optimized to avoid allocation (99.9% improvement for large numbers)

2022-06-07 23:31 UTC, tczajka requested changes

2022-06-07 23:31 UTC, tczajka commented on tests/bits.rs
> -            assert_eq!(&a_big & b_big.clone(), res);
Why delete this test?

2022-06-07 23:31 UTC, tczajka commented on src/bits.rs
> +            (Negative, v) => !v.wrapping_sub(T::from(1u8)),
How about `T::from(0u8).wrapping_sub(v)`.

2022-06-07 23:31 UTC, tczajka commented on src/bits.rs
> +            (Negative, v) => !v.wrapping_sub(T::from(1u8)),
`T::from(0u8).wrapping_sub(v)`

2022-06-12 08:12 UTC, kakogi commented on tests/bits.rs
> -            assert_eq!(&a_big & b_big.clone(), res);
Accident.

2022-06-12 08:13 UTC, kakogi commented on src/bits.rs
> +            (Negative, v) => !v.wrapping_sub(T::from(1u8)),
Yes.

2022-06-12 08:13 UTC, kakogi commented on src/bits.rs
> +            (Negative, v) => !v.wrapping_sub(T::from(1u8)),
Yes.

2022-06-13 21:36 UTC, tczajka commented on src/primitive.rs
> +    fn as_unsigned(self) -> Self::Unsigned;
I believe this violates the standard naming conventions (https://rust-lang.github.io/api-guidelines/naming.html) -- `as_something` something is supposed to take reference and return reference.

So I suggest: `wrapping_to_unsigned` and `wrapping_from_unsigned`.

2022-07-01 23:21 UTC, tczajka commented
Closing -- I don't want to use different algorithms for primitives while leaving the IBig & IBig algorithms slow. 

Instead -- the algorithms for IBig will soon be fixed properly.

2022-07-01 23:21 UTC, closed without merging